development:
  adapter: postgresql
  encoding: unicode
  database: hundred_development
  pool: 5
  username: arvindravi
  password: hundred

test:
  adapter: postgresql
  encoding: unicode
  database: hundred_test
  pool: 5
  username: arvindravi
  password: hundred
